[features]
seeds = false
[programs.localnet]
grants_program = "2BAJJedFtdAEv8BdDcQwnQEYuBieqkz3Yzdg8feBiCXc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/thefunnyintrovert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
